---

services:
#  app:
#    build: ..
#    ports:
#      - "8080:8080"
#    env_file:
#      - ../.env
#    depends_on:
#      - postgres
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - ../.env
    volumes:
      - ../pgdata:/var/lib/postgresql/data
