---

services:
  app:
    build: ..
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - ../.env
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  migrate:
    build: ..
    container_name: migrate
    command: alembic upgrade head
    env_file:
      - ../.env
    depends_on:
      - postgres
    restart: "no"
