---

services:
  postgres:
    build: ../postgres
    container_name: postgres
    env_file:
      - ../.env
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  migrate:
    image: ghcr.io/gifi71/amazur-devops-test:latest
    build: ..
    container_name: migrate
    command: alembic upgrade head
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  app:
    image: ghcr.io/gifi71/amazur-devops-test:latest
    build: ..
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/health')"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

