---

services:
  postgres:
    build: ../postgres
    container_name: postgres
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  migrate:
    build: ..
    container_name: migrate
    command: alembic upgrade head
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  app:
    build: ..
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
        
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/health')"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 5s


volumes:
  pgdata: