name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install cosign (skip on PR)
      - name: Install cosign
        if: ${{ github.event_name != 'pull_request' }}
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Docker login (skip on PR)
      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # 6. Build Docker image with Buildx (don't push on PR)
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 7. Create .env
      - name: Create .env for CI
        run: |
          cp .env.example .env

      # 8. Run containers and wait for healthcheck
      - name: Start containers and wait for health
        run: |
          cd deploy
          docker compose up -d
          echo "Waiting for services to become healthy..."
          for service in app postgres; do
            for i in {1..12}; do
              status=$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q $service))
              echo "$service health: $status"
              if [ "$status" = "healthy" ]; then
                break
              fi
              sleep 5
            done
            if [ "$status" != "healthy" ]; then
              echo "ERROR: $service did not become healthy in time"
              exit 1  # <- workflow упадёт здесь
            fi
          done

      # 9. Push Docker image (skip on PR)
      - name: Push Docker image
        id: push-image
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      # 10. Sign the published Docker image (skip on PR)
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.push-image.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # 11. Stop and remove containers
      - name: Stop containers
        if: always()
        run: cd deploy && docker compose down
