name: CI Pipeline

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13.3
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install dev dependencies
        run: pip install -r requirements/dev.txt

      - name: Run flake8
        run: flake8 app/

      - name: Run black
        run: black --check app/

      - name: Run isort
        run: isort --check-only app/
      
      - name: Run mypy
        run: mypy app/


  build-image:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Docker image to artifact
        run: |
          TAG=${{ steps.docker_build.outputs.tags }}
          docker save "$TAG" | gzip > image.tar.gz
        shell: bash

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz


  integration-tests:
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < image.tar.gz

      - name: Create .env for CI
        run: cp .env.example .env

      - name: Start containers and wait for health
        run: |
          cd deploy
          docker compose up -d
          echo "Waiting for services to become healthy..."
          for service in app postgres; do
            for i in {1..12}; do
              status=$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q $service))
              echo "$service health: $status"
              if [ "$status" = "healthy" ]; then
                break
              fi
              sleep 5
            done
            if [ "$status" != "healthy" ]; then
              echo "ERROR: $service did not become healthy in time"
              exit 1
            fi
          done

      - name: Run integration tests
        run: |
          pip install -r requirements/dev.txt
          pytest -v app/tests

      - name: Stop containers
        if: always()
        run: cd deploy && docker compose down


  push-and-sign:
    if: ${{ github.event_name != 'pull_request' }}
    needs: integration-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign (only on non-PR)
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build with cache and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
